### ISSUE TITLE
unmet dependency (version) for node-sass and can't find coffee-script

### ISSUE THREAD

**Issue by kernelsmith** [hakimel/reveal.js#1224]
after I

```Shell
brew install node
npm install -g grunt-cli
git clone git@github.com:hakimel/reveal.js.git
cd reveal.js
# and then
npm install
```

* OS X obviously, 14.3.0 Darwin Kernel Version 14.3.0; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
* npm -v => 2.7.5
* node -v => v0.12.2

I get an error indicating node-sass@'0.9.3' is required but will load <blank here>
If I then

```
npm install node-sass
```
the error will turn into node-sass@'0.9.3' is required but will load node-sass@'0.9.3'
I then:

```
npm install node-sass@'0.9.3'
npm install # will then complete normally
```
However, I then get the following when I grunt serve:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/presentation/path/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I don't know jack squat about node/npm, but I'm familiar w/Ruby/Bundler, so was wondering if you think this is related to the node equivalent of the Gemfile not specifying the node-sass version, which maybe has since been updated to 0.9.6?  Or, is this likely a local environment problem?  I admit I've gone through this process a few times, and therefore my environment may not be totally pristine.

Thanks

**Comment by kernelsmith** [comment]
Nevermind, the old:

```Shell
rm -rf node_modules/
npm cache clean
npm install again #make sure not to interupt
```
worked this time
