### ISSUE TITLE
"Failed at the reveal.js@3.3.0 start script 'grunt serve'"

### ISSUE THREAD

**Issue by timcsmith** [hakimel/reveal.js#1650]
Trying to npm local

git clone https://github.com/hakimel/reveal.js.git
cd reveal.js
npm install 
npm start 

I get an error when attempting to start the server (last command). 

Here is the output from npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart reveal.js@3.3.0
6 info start reveal.js@3.3.0
7 verbose unsafe-perm in lifecycle true
8 info reveal.js@3.3.0 Failed to exec start script
9 verbose stack Error: reveal.js@3.3.0 start: `grunt serve`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid reveal.js@3.3.0
11 verbose cwd E:\Dropbox\Reveal.JS\reveal.js
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error reveal.js@3.3.0 start: `grunt serve`
17 error Exit status 1
18 error Failed at the reveal.js@3.3.0 start script 'grunt serve'.
18 error This is most likely a problem with the reveal.js package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt serve
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs reveal.js
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls reveal.js
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by lukaszklis** [comment]
Faced the same issue, found a "workaround" by changing the path to `grunt` executable in `package.json` file to the following:

```json
{
  "scripts": {
    "test": "./node_modules/.bin/grunt test",
    "serve": "./node_modules/.bin/grunt serve"
  }
}
```

It might not be an ideal approach to this, though.

**Comment by demoneaux** [comment]
This seems like an npm issue. AFAIK, npm will automatically add `node_modules/.bin` to the PATH when running, so adding the full path to the grunt executable shouldn't be necessary. Perhaps you could try removing all dependencies and reinstalling with npm, or updating your npm version.
