### ISSUE TITLE
npm install not working on Win7x64 with node8.4

### ISSUE THREAD

**Issue by TypedSource** [hakimel/reveal.js#1975]
looks like the sass library does not work on windows

here is the output:

```
npm install

> node-sass@3.13.1 install D:\coding\test\reveal.js\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall D:\coding\test\reveal.js\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\coding\test\reveal.js\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\coding\\test\\reveal.js\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\coding\test\reveal.js\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\coding\test\reveal.js\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\coding\test\reveal.js\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\coding\test\reveal.js\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\coding\test\reveal.js\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\coding\test\reveal.js\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:13:12)\n    at F (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:68:19)\n    at E (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:80:29)\n    at D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:89:16\n    at D:\\coding\\test\\reveal.js\\node_modules\\isexe\\index.js:42:5\n    at D:\\coding\\test\\reveal.js\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\coding\test\reveal.js\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\coding\test\reveal.js\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\coding\test\reveal.js\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\coding\test\reveal.js\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\coding\test\reveal.js\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\coding\test\reveal.js\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\coding\test\reveal.js\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:13:12)\n    at F (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:68:19)\n    at E (D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:80:29)\n    at D:\\coding\\test\\reveal.js\\node_modules\\which\\which.js:89:16\n    at D:\\coding\\test\\reveal.js\\node_modules\\isexe\\index.js:42:5\n    at D:\\coding\\test\\reveal.js\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\coding\test\reveal.js\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\coding\test\reveal.js\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\coding\test\reveal.js\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\coding\\test\\reveal.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\coding\test\reveal.js\node_modules\node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by MichaelNeas** [comment]
Did you try downloading and setting it in your environmental variables?

 `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

**Comment by coelsner** [comment]
It seems to be an error with node 8. I switched to node 6 and now its working. 

The searched version (57) of sass doesn't exists (see https://github.com/sass/node-sass/releases/tag/v3.13.1)

If I run it with node 6 it uses a right version (48)

**Comment by bnjmnt4n** [comment]
Seems like an error with Node and npm at that time. Using the latest version of npm for Node 8 should fix that. See https://github.com/sass/node-sass/issues/1991 for more info.

**Comment by makayabou** [comment]
Same Problem with node.js and npm v12.14.0-r0 on latest Alpine (docker)
