### ISSUE TITLE
Npm install: Issue installing puppeteer

### ISSUE THREAD

**Issue by hamzahamidi** [hakimel/reveal.js#2445]
When running ```npm install``` I have the following problem:
```bash

λ npm i 

> puppeteer@1.18.1 install C:\hha\reveal.js\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r672088! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 216.58.204.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (C:\hha\reveal.js\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> (C:\hha\reveal.js\node_modules\puppeteer\install.js:64:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '216.58.204.112',
  port: 443 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.18.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.18.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\S644209\AppData\Roaming\npm-cache\_logs\2019-07-01T09_53_56_566Z-debug.log

```
### Info
OS: Windows 10 
Node Version: v8.12.0
Npm Version: v6.4.1

**Comment by hamzahamidi** [comment]
I found the solution. I run the following command:
```bash
Set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false&npm i puppeteer
 ```
