### ISSUE TITLE
Doesn't compile out of the box on MacOS 10.14.6

### ISSUE THREAD

**Issue by eyesno** [hakimel/reveal.js#2529]
First problem encountered was that gyp failed because there was no "python2" executable in the path. I solved this by installing python@2 using brew. 

Now there are C++ compiler errors with it building the command line tools. It's not clear why it's actually building any command-line tools since they are installed via Xcode already. 

Log attached.

[2019-11-17T16_39_53_152Z-debug.log](https://github.com/hakimel/reveal.js/files/3855832/2019-11-17T16_39_53_152Z-debug.log)

**Comment by lcervantesm** [comment]
Had the same issue, git checkout dev do the trick. Thank you.

**Comment by nickyfoto** [comment]
Had same issue on 10.15.2, use the dev trick.

**Comment by StevenMacias** [comment]
Something similar just happen to me in Manjaro Linux. It doesn't work right out of the box with *python 3.9*. I created a conda environment with *python 3.6*, same error. Only when I created a conda environment with python 2. 7 I was able to do `npm install`. The error traces with *python 3.8.5* look like: 

```
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/steven/workspace/github/others/test/reveal.js/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/steven/workspace/github/others/test/reveal.js/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/steven/workspace/github/others/test/reveal.js/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/steven/workspace/github/others/test/reveal.js/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/steven/workspace/github/others/test/reveal.js/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/steven/workspace/github/others/test/reveal.js/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /home/steven/anaconda3/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/steven/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:327:12)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Linux 5.10.15-1-MANJARO
gyp ERR! command "/usr/bin/node" "/home/steven/workspace/github/others/test/reveal.js/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/steven/workspace/github/others/test/reveal.js/node_modules/node-sass
gyp ERR! node -v v15.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steven/.npm/_logs/2021-02-14T16_04_07_695Z-debug.log

```

It seems that node needs `node-gyp` that at the same time uses python. However, I checked its github [repo](https://github.com/nodejs/node-gyp#on-unix) and states that needs `Python v3.6, v3.7, v3.8, or v3.9`, so maybe reveal.js is using an old version of node-gyp?
