### ISSUE TITLE
Strange Warning

### ISSUE THREAD

**Issue by lanmaster53** [hakimel/reveal.js#2630]
I get this every time I start Reveal.js with `npm start --verbose`. Any idea why? Looks like it could break things moving forward based on the message.

```
revealjs | > reveal.js@3.9.2 start /revealjs
revealjs | > grunt serve
revealjs | 
revealjs | Running "connect:server" (connect) task
revealjs | Started connect web server on http://localhost:8000
revealjs | 
revealjs | Running "watch" task
revealjs | Waiting...
revealjs | (node:18) UnhandledPromiseRejectionWarning: Error: Exited with code 3
revealjs |   at ChildProcess.<anonymous> (/revealjs/node_modules/opn/index.js:84:13)
revealjs |   at Object.onceWrapper (events.js:423:26)
revealjs |   at ChildProcess.emit (events.js:316:20)
revealjs |   at maybeClose (internal/child_process.js:1026:16)
revealjs |   at Socket.<anonymous> (internal/child_process.js:441:11)
revealjs |   at Socket.emit (events.js:316:20)
revealjs |   at Pipe.<anonymous> (net.js:672:12)
revealjs | 
revealjs | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
revealjs | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KRostyslav** [comment]
@lanmaster53 the same.
Did you find the solution?

**Comment by lanmaster53** [comment]
I just let it be. It doesn't prevent it from working. It's just annoying.
