### ISSUE TITLE
gulp serve

### ISSUE THREAD

**Issue by ennatmm** [hakimel/reveal.js#2884]
npm ERR! Failed at the reveal.js@4.1.0 start script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reveal.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reveal.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reveal.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ankl_admin/Documents/github/reveal.js/npm-debug.log
can't trace npm-debug.log

**Comment by billbrod** [comment]
I was having a similar issue, as pasted below: 

```
>>> npm start 

> reveal.js@4.1.0 start /home/billbrod/reveal.js
> gulp serve

[15:04:16] Using gulpfile ~/reveal.js/gulpfile.js
[15:04:16] Starting 'serve'...
[15:04:16] Starting server...
[15:04:16] 'serve' errored after 29 ms
[15:04:16] Error: listen EADDRINUSE: address already in use 0.0.0.0:8000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reveal.js@4.1.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reveal.js@4.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/billbrod/.npm/_logs/2021-03-12T20_04_16_270Z-debug.log
```

It turns out the problem was just that port `8000` was already in use. I think an earlier version of `reveal.js` would automatically jump to the next available port when this was the case, but now I had to specify it myself, as per the instructions: `npm start -- --port=8001`
