### ISSUE TITLE
qunit fails at 'test/test-markdown.html'

### ISSUE THREAD

**Issue by ChuangSheep** [hakimel/reveal.js#2921]
When I run gulp test with preset gulpfile.js, the task `qunit` errors with following info:
<details>
PS F:\repos\presentations\reveal.js> gulp qunit
[19:53:05] Using gulpfile F:\repos\presentations\reveal.js\gulpfile.js
[19:53:05] Starting 'qunit'...
[19:53:05] Starting server...
[19:53:05] test-server started http://0.0.0.0:8009
[19:53:05] Running server
Error: net::ERR_ADDRESS_INVALID at http://0.0.0.0:8009/test/test-auto-animate.html
    at navigate (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\FrameManager.js:94:17)
    at async Frame.goto (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\FrameManager.js:406:12)
    at async Page.goto (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\Page.js:672:12)
    at async Object.runQunitPuppeteer (F:\repos\presentations\reveal.js\node_modules\node-qunit-puppeteer\index.js:266:5)
  -- ASYNC --
    at Frame.<anonymous> (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (F:\repos\presentations\reveal.js\node_modules\puppeteer\lib\helper.js:112:23)
    at Object.runQunitPuppeteer (F:\repos\presentations\reveal.js\node_modules\node-qunit-puppeteer\index.js:266:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[19:53:06] 'qunit' errored after 1.11 s
[19:53:06] Error: Promise rejected without Error
    at onError (F:\repos\presentations\reveal.js\node_modules\async-done\index.js:49:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
</details>

After I changed the server host to 127.0.0.1, most tests pass but 	`test/test-markdown.html`:

```
    let serverConfig = {
        root,
        port: 8009,
        host: '127.0.0.1',
        name: 'test-server'
    }
```

```
! test/test-markdown.html [0/1] in 8ms
Module: 
  Test: global failure
    Status: failed
    Failed assertions: 1 of 1
    Elapsed: 1ms
    Log
      Result: false, Expected: undefined, Actual: null, Message: Uncaught TypeError: _o is not a function
      Stacktrace: TypeError: _o is not a function
          at http://127.0.0.1:8009/plugin/markdown/markdown.esm.js:1:4268
```

Full message:
<details>
PS F:\repos\presentations\reveal.js> gulp qunit
[19:52:50] Using gulpfile F:\repos\presentations\reveal.js\gulpfile.js
[19:52:50] Starting 'qunit'...
[19:52:50] Starting server...
[19:52:50] test-server started http://localhost:8009
[19:52:50] Running server
✔ test/test-dependencies.html [1/1] in 6ms
✔ test/test-dependencies-async.html [5/5] in 336ms
✔ test/test-pdf.html [1/1] in 7ms
! test/test-markdown.html [0/1] in 8ms
Module: 
  Test: global failure
    Status: failed
    Failed assertions: 1 of 1
    Elapsed: 1ms
    Log
      Result: false, Expected: undefined, Actual: null, Message: Uncaught TypeError: _o is not a function
      Stacktrace: TypeError: _o is not a function
          at http://localhost:8009/plugin/markdown/markdown.esm.js:1:4268
✔ test/test-state.html [6/6] in 152ms
✔ test/test-grid-navigation.html [4/4] in 84ms
✔ test/test-plugins.html [9/9] in 1019ms
✔ test/test-multiple-instances-es5.html [8/8] in 69ms
✔ test/test-iframes.html [14/14] in 86ms
✔ test/test-auto-animate.html [14/14] in 278ms
✔ test/test.html [146/146] in 627ms
✔ test/test-iframe-backgrounds.html [12/12] in 113ms
[19:52:55] 'qunit' errored after 5.04 s
[19:52:55] Error: 1/232 tests failed
    at F:\repos\presentations\reveal.js\gulpfile.js:221:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
</details>

I appreciate any hint about what happened.

**Comment by ChuangSheep** [comment]
I do believe the plugins are messed up by 'gulp js' but I don't know why. I didn't change anything there.
