### ISSUE TITLE
During install - ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by stpaultim** [hakimel/reveal.js#3389]
I am trying to follow the installation instructions for Full Setup and get the following error upon running `npm start`.

```
> reveal.js@4.4.0 start
> gulp serve

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/puppeteer-core.js' is not defined by "exports" in /home/tim/sites/test/reveal.js/node_modules/puppeteer-core/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/tim/sites/test/reveal.js/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js:33:14)
    at Module._compile (internal/modules/cjs/loader.js:1076:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
node --version = v14.10.1
OS = Ubuntu 22.04.2 LTS

**Comment by stpaultim** [comment]
I have since been able to get this working. I thought I was using latest versions of NPM, NVM, and node. After ensuring that I am on recent version of each, this seems to be working. 

node: 18.0.0
npm: 8.6.0
nvm: 0.38.0

Thanks to everyone working on this project.
