### ISSUE TITLE
TypeError: Cannot read properties of undefined (in sass.dart.js)

### ISSUE THREAD

**Issue by polla-fattah** [hakimel/reveal.js#3500]
Freshly installed reveal.js gives error at start on  Windows 10

$ node --version
v21.0.0

$ npm -v
10.2.0

$ git clone https://github.com/hakimel/reveal.js.git
Cloning into 'reveal.js'...
remote: Enumerating objects: 16527, done.
remote: Counting objects: 100% (579/579), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 16527 (delta 426), reused 489 (delta 386), pack-reused 15948
Receiving objects: 100% (16527/16527), 22.09 MiB | 3.02 MiB/s, done.
Resolving deltas: 100% (9566/9566), done.

$ cd reveal.js && npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 855 packages, and audited 856 packages in 14s

49 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm start

> reveal.js@4.6.1 start
> gulp serve

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:94455:12
    at Object.applyHooksTransformer (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:7258:14)
    at Object.initHooks (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:7238:251)
    at Object.initNativeDispatchContinue (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:7204:9)
    at Object.initNativeDispatch (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:7198:9)
    at Object.getNativeInterceptor (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:9092:13)
    at Object.getInterceptor$x (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:9348:16)
    at Object.set$render$x (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:9385:16)
    at main0 (C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:17809:9)
    at C:\Users\pollafattah\OneDrive\Desktop\reveal.js\node_modules\sass\sass.dart.js:95897:7

**Comment by andrewmiron** [comment]
Upgrade to next node version (21.1.0) and the problem will not show anymore. Looks like the issue is generated by node rather than reveal.js. Check also npm is at 10.2.0.

**Comment by polla-fattah** [comment]
Thanks it really turns out it was the version of node and npm
